export const translations = {
  de: {
    nav: { shop: 'Honig', beekeeping: 'Imkerei', about: 'Über uns', contact: 'Kontakt', cart: 'Warenkorb', openMenu: 'Menü öffnen', closeMenu: 'Menü schließen', cartAria: 'Warenkorb, {count} Artikel' },
    home: { eyebrow: 'ECHTER HONIG AUS DEM ODENWALD', heroTitle: 'Ein Stück|Odenwald|im Glas.', heroText: 'Regionaler Honig, mit Sorgfalt gewonnen und dort abgefüllt, wo unsere Bienenvölker zuhause sind.', discover: 'Honig entdecken', introEyebrow: 'GELOBTES LAND', introTitle: 'Honig mit Herkunft.', introText: 'Der Odenwald ist mehr als ein Ort auf der Landkarte. Wälder, Wiesen und Blüten prägen die Landschaft — und den Charakter unseres Honigs.', more: 'Mehr über uns', productsEyebrow: 'AUS UNSERER IMKEREI', productsTitle: 'Unsere Honige', allProducts: 'Alle Produkte', homeEyebrow: 'UNSER ZUHAUSE', homeTitle: 'Der Odenwald.', homeText: 'Hier wachsen die Blüten, hier stehen unsere Völker, hier beginnt die Reise jedes Glases Gelobtes Land.', beekeeping: 'Unsere Imkerei', valuesEyebrow: 'WAS UNS WICHTIG IST', valuesTitle: 'Natürlich. Regional. Sorgfältig.', value1Title: 'Aus dem Odenwald', value1Text: 'Unsere Honige entstehen in einer Landschaft, die wir kennen und schätzen.', value2Title: 'Im Rhythmus der Natur', value2Text: 'Wir arbeiten mit unseren Bienenvölkern und respektieren ihren natürlichen Rhythmus.', value3Title: 'Mit Sorgfalt', value3Text: 'Von der Ernte bis zum Glas achten wir auf Qualität und einen schonenden Umgang.', ctaEyebrow: 'GELOBTES LAND', ctaTitle: 'Ein Glas Odenwald für zuhause.', shop: 'Zum Shop' },
    shop: { eyebrow: 'AUS UNSERER IMKEREI', title: 'Honig', text: 'Entdecke unsere aktuellen Produkte aus dem Odenwald.' },
    product: { notFound: 'Produkt nicht gefunden', back: 'Zurück zum Shop', add: 'In den Warenkorb', regional: 'Regional aus dem Odenwald', bottled: 'Sorgfältig abgefüllt', shipping: 'Versand innerhalb Deutschlands', honey: 'Honig' },
    cart: { eyebrow: 'DEIN EINKAUF', title: 'Warenkorb', emptyTitle: 'Dein Warenkorb ist leer.', emptyText: 'Entdecke unseren Honig aus dem Odenwald.', summary: 'Zusammenfassung', subtotal: 'Zwischensumme', shipping: 'Versand', total: 'Gesamt', checkout: 'Zur Kasse', vat: 'Inklusive gesetzlicher MwSt., soweit anwendbar.', remove: 'Entfernen' },
    checkout: { eyebrow: 'SICHER BESTELLEN', title: 'Zur Kasse', contact: 'Kontaktdaten', email: 'E-Mail', addressTitle: 'Lieferadresse', firstName: 'Vorname', lastName: 'Nachname', address: 'Straße und Hausnummer', zip: 'PLZ', city: 'Ort', country: 'Land', countries: { DE: 'Deutschland', AT: 'Österreich', ES: 'Spanien' }, order: 'Deine Bestellung', payment: 'Weiter zur Zahlung', loading: 'Weiter zu Stripe…', empty: 'Warenkorb ist leer.', secure: 'Zahlung wird sicher über Stripe abgewickelt. Kartendaten werden nicht von Gelobtes Land gespeichert.', stripeError: 'Stripe Checkout URL fehlt.' },
    result: { successEyebrow: 'BESTELLUNG ERFOLGREICH', successTitle: 'Danke für deine Bestellung.', successText: 'Wir haben deine Zahlung erhalten. {extra}', processing: 'Deine Bestellung wird jetzt verarbeitet.', continue: 'Weiter einkaufen', cancelEyebrow: 'ZAHLUNG ABGEBROCHEN', cancelTitle: 'Deine Bestellung wurde nicht abgeschlossen.', cancelText: 'Deine Artikel bleiben im Warenkorb.', back: 'Zurück zur Kasse' },
    footer: { copy: 'Echter Honig aus dem Odenwald — regional, sorgfältig gewonnen und natürlich abgefüllt.', shop: 'Shop', honey: 'Honig', about: 'Über uns', beekeeping: 'Unsere Imkerei', contact: 'Kontakt', info: 'Informationen', shipping: 'Versand', imprint: 'Impressum', privacy: 'Datenschutz', withdrawal: 'Widerruf' },
    content: { about: ['GELOBTES LAND', 'Honig mit Herkunft.', 'Gelobtes Land steht für Honig aus dem Odenwald und für eine Imkerei, die eng mit ihrer Landschaft verbunden ist.', 'Diese Seite ist als echter Markenbereich vorbereitet und kann später mit euren eigenen Geschichten, Bildern und Betriebsinformationen ergänzt werden.'], beekeeping: ['UNSERE IMKEREI', 'Arbeiten mit der Natur.', 'Unsere Bienenvölker stehen dort, wo Wälder, Wiesen und Blüten den Odenwald prägen. Jede Ernte erzählt deshalb ein Stück ihrer Umgebung.', 'Hier können später eure tatsächlichen Standorte, Arbeitsweise, Ernteprozesse und Bilder aus der Imkerei veröffentlicht werden.'], contact: ['KONTAKT', 'Wir freuen uns auf deine Nachricht.', 'Für Fragen zu Produkten, Bestellungen oder unserer Imkerei erreichst du uns per E-Mail.', 'info@odenwald-honig.com'], shipping: ['INFORMATIONEN', 'Versand', 'Der Versand wird innerhalb Deutschlands über einen geeigneten Paketdienst abgewickelt. Die konkreten Versandkosten und Lieferzeiten werden vor dem Kauf transparent angezeigt.'], imprint: ['RECHTLICHES', 'Impressum', 'Gelobtes Land', 'Die vollständigen Anbieterangaben werden vor dem Livegang ergänzt.'], privacy: ['RECHTLICHES', 'Datenschutz', 'Die finale Datenschutzerklärung wird vor dem Livegang auf Basis der tatsächlich eingesetzten Dienste, insbesondere Hosting, Authentifizierung, Zahlungsanbieter und Analytics, ergänzt.'], withdrawal: ['RECHTLICHES', 'Widerrufsbelehrung', 'Die finale Widerrufsbelehrung wird vor dem Livegang anhand des tatsächlichen Sortiments und der rechtlichen Anforderungen erstellt.'] },
    languages: { de: 'DE', en: 'EN', es: 'ES' }
  },
  en: {
    nav: { shop: 'Honey', beekeeping: 'Beekeeping', about: 'About us', contact: 'Contact', cart: 'Cart', openMenu: 'Open menu', closeMenu: 'Close menu', cartAria: 'Cart, {count} items' },
    home: { eyebrow: 'REAL HONEY FROM THE ODENWALD', heroTitle: 'A piece of|Odenwald|in every jar.', heroText: 'Regional honey, carefully harvested and bottled where our bee colonies call home.', discover: 'Discover our honey', introEyebrow: 'GELOBTES LAND', introTitle: 'Honey with a sense of place.', introText: 'The Odenwald is more than a place on the map. Forests, meadows and blossoms shape the landscape — and the character of our honey.', more: 'More about us', productsEyebrow: 'FROM OUR APIARY', productsTitle: 'Our honey', allProducts: 'All products', homeEyebrow: 'OUR HOME', homeTitle: 'The Odenwald.', homeText: 'This is where the blossoms grow, our colonies live, and the journey of every Gelobtes Land jar begins.', beekeeping: 'Our beekeeping', valuesEyebrow: 'WHAT MATTERS TO US', valuesTitle: 'Natural. Local. Careful.', value1Title: 'From the Odenwald', value1Text: 'Our honey comes from a landscape we know and value.', value2Title: 'In nature’s rhythm', value2Text: 'We work with our colonies and respect their natural rhythm.', value3Title: 'With care', value3Text: 'From harvest to jar, we focus on quality and gentle handling.', ctaEyebrow: 'GELOBTES LAND', ctaTitle: 'A taste of the Odenwald at home.', shop: 'Visit the shop' },
    shop: { eyebrow: 'FROM OUR APIARY', title: 'Honey', text: 'Discover our current selection from the Odenwald.' },
    product: { notFound: 'Product not found', back: 'Back to shop', add: 'Add to cart', regional: 'From the Odenwald', bottled: 'Carefully bottled', shipping: 'Shipping within Germany', honey: 'Honey' },
    cart: { eyebrow: 'YOUR PURCHASE', title: 'Cart', emptyTitle: 'Your cart is empty.', emptyText: 'Discover our honey from the Odenwald.', summary: 'Summary', subtotal: 'Subtotal', shipping: 'Shipping', total: 'Total', checkout: 'Checkout', vat: 'Including statutory VAT, where applicable.', remove: 'Remove' },
    checkout: { eyebrow: 'SECURE CHECKOUT', title: 'Checkout', contact: 'Contact details', email: 'Email', addressTitle: 'Delivery address', firstName: 'First name', lastName: 'Last name', address: 'Street and house number', zip: 'Postcode', city: 'City', country: 'Country', countries: { DE: 'Germany', AT: 'Austria', ES: 'Spain' }, order: 'Your order', payment: 'Continue to payment', loading: 'Continue to Stripe…', empty: 'Your cart is empty.', secure: 'Payment is securely processed by Stripe. Gelobtes Land does not store card details.', stripeError: 'Stripe Checkout URL is missing.' },
    result: { successEyebrow: 'ORDER SUCCESSFUL', successTitle: 'Thank you for your order.', successText: 'We received your payment. {extra}', processing: 'Your order is now being processed.', continue: 'Continue shopping', cancelEyebrow: 'PAYMENT CANCELLED', cancelTitle: 'Your order was not completed.', cancelText: 'Your items are still in your cart.', back: 'Back to checkout' },
    footer: { copy: 'Real honey from the Odenwald — local, carefully harvested and naturally bottled.', shop: 'Shop', honey: 'Honey', about: 'About us', beekeeping: 'Our beekeeping', contact: 'Contact', info: 'Information', shipping: 'Shipping', imprint: 'Legal notice', privacy: 'Privacy', withdrawal: 'Withdrawal' },
    content: { about: ['GELOBTES LAND', 'Honey with a sense of place.', 'Gelobtes Land stands for honey from the Odenwald and an apiary closely connected to its landscape.', 'This area is prepared to become a real brand story with your own history, images and farm information.'], beekeeping: ['OUR APIARY', 'Working with nature.', 'Our colonies live where forests, meadows and blossoms shape the Odenwald. Every harvest therefore carries something of its surroundings.', 'Your actual locations, methods, harvest process and images can be published here later.'], contact: ['CONTACT', 'We would love to hear from you.', 'For questions about products, orders or our apiary, contact us by email.', 'info@odenwald-honig.com'], shipping: ['INFORMATION', 'Shipping', 'Orders are shipped within Germany using a suitable parcel carrier. Exact shipping costs and delivery times are shown transparently before purchase.'], imprint: ['LEGAL', 'Legal notice', 'Gelobtes Land', 'Complete provider information will be added before launch.'], privacy: ['LEGAL', 'Privacy', 'The final privacy policy will be completed before launch based on the services actually used, including hosting, authentication, payment providers and analytics.'], withdrawal: ['LEGAL', 'Withdrawal policy', 'The final withdrawal policy will be prepared before launch based on the actual product range and applicable legal requirements.'] },
    languages: { de: 'DE', en: 'EN', es: 'ES' }
  },
  es: {
    nav: { shop: 'Miel', beekeeping: 'Apicultura', about: 'Sobre nosotros', contact: 'Contacto', cart: 'Carrito', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú', cartAria: 'Carrito, {count} artículos' },
    home: { eyebrow: 'MIEL REAL DEL ODENWALD', heroTitle: 'Un pedazo del|Odenwald|en cada tarro.', heroText: 'Miel local, recolectada con cuidado y envasada allí donde viven nuestras abejas.', discover: 'Descubrir nuestra miel', introEyebrow: 'GELOBTES LAND', introTitle: 'Miel con origen.', introText: 'El Odenwald es mucho más que un lugar en el mapa. Bosques, praderas y flores dan forma al paisaje y al carácter de nuestra miel.', more: 'Más sobre nosotros', productsEyebrow: 'DE NUESTRA APICULTURA', productsTitle: 'Nuestras mieles', allProducts: 'Todos los productos', homeEyebrow: 'NUESTRO HOGAR', homeTitle: 'El Odenwald.', homeText: 'Aquí crecen las flores, aquí viven nuestras colmenas y aquí comienza el viaje de cada tarro de Gelobtes Land.', beekeeping: 'Nuestra apicultura', valuesEyebrow: 'LO QUE NOS IMPORTA', valuesTitle: 'Natural. Local. Con cuidado.', value1Title: 'Del Odenwald', value1Text: 'Nuestra miel nace en un paisaje que conocemos y valoramos.', value2Title: 'Al ritmo de la naturaleza', value2Text: 'Trabajamos con nuestras colmenas y respetamos su ritmo natural.', value3Title: 'Con cuidado', value3Text: 'Desde la cosecha hasta el tarro, cuidamos la calidad y un tratamiento delicado.', ctaEyebrow: 'GELOBTES LAND', ctaTitle: 'Un poco del Odenwald en tu casa.', shop: 'Ir a la tienda' },
    shop: { eyebrow: 'DE NUESTRA APICULTURA', title: 'Miel', text: 'Descubre nuestros productos actuales del Odenwald.' },
    product: { notFound: 'Producto no encontrado', back: 'Volver a la tienda', add: 'Añadir al carrito', regional: 'Del Odenwald', bottled: 'Envasado con cuidado', shipping: 'Envíos dentro de Alemania', honey: 'Miel' },
    cart: { eyebrow: 'TU COMPRA', title: 'Carrito', emptyTitle: 'Tu carrito está vacío.', emptyText: 'Descubre nuestra miel del Odenwald.', summary: 'Resumen', subtotal: 'Subtotal', shipping: 'Envío', total: 'Total', checkout: 'Finalizar compra', vat: 'IVA legal incluido cuando corresponda.', remove: 'Eliminar' },
    checkout: { eyebrow: 'COMPRA SEGURA', title: 'Finalizar compra', contact: 'Datos de contacto', email: 'E-mail', addressTitle: 'Dirección de entrega', firstName: 'Nombre', lastName: 'Apellidos', address: 'Calle y número', zip: 'Código postal', city: 'Ciudad', country: 'País', countries: { DE: 'Alemania', AT: 'Austria', ES: 'España' }, order: 'Tu pedido', payment: 'Continuar al pago', loading: 'Continuar a Stripe…', empty: 'Tu carrito está vacío.', secure: 'El pago se procesa de forma segura mediante Stripe. Gelobtes Land no almacena los datos de la tarjeta.', stripeError: 'Falta la URL de Stripe Checkout.' },
    result: { successEyebrow: 'PEDIDO REALIZADO', successTitle: 'Gracias por tu pedido.', successText: 'Hemos recibido tu pago. {extra}', processing: 'Tu pedido se está procesando.', continue: 'Seguir comprando', cancelEyebrow: 'PAGO CANCELADO', cancelTitle: 'El pedido no se ha completado.', cancelText: 'Tus artículos siguen en el carrito.', back: 'Volver al checkout' },
    footer: { copy: 'Miel real del Odenwald — local, recolectada con cuidado y envasada de forma natural.', shop: 'Tienda', honey: 'Miel', about: 'Sobre nosotros', beekeeping: 'Nuestra apicultura', contact: 'Contacto', info: 'Información', shipping: 'Envíos', imprint: 'Aviso legal', privacy: 'Privacidad', withdrawal: 'Desistimiento' },
    content: { about: ['GELOBTES LAND', 'Miel con origen.', 'Gelobtes Land representa la miel del Odenwald y una apicultura estrechamente vinculada a su paisaje.', 'Esta sección está preparada para incorporar vuestra historia, imágenes e información real del proyecto.'], beekeeping: ['NUESTRA APICULTURA', 'Trabajar con la naturaleza.', 'Nuestras colmenas están donde los bosques, praderas y flores dan forma al Odenwald. Por eso cada cosecha lleva algo de su entorno.', 'Aquí podremos publicar más adelante vuestros emplazamientos, métodos de trabajo, procesos de cosecha e imágenes.'], contact: ['CONTACTO', 'Estaremos encantados de recibir tu mensaje.', 'Para preguntas sobre productos, pedidos o nuestra apicultura, puedes escribirnos por e-mail.', 'info@odenwald-honig.com'], shipping: ['INFORMACIÓN', 'Envíos', 'Los pedidos se envían dentro de Alemania mediante un servicio de paquetería adecuado. Los costes y plazos exactos se muestran antes de comprar.'], imprint: ['LEGAL', 'Aviso legal', 'Gelobtes Land', 'Los datos completos del responsable se añadirán antes del lanzamiento.'], privacy: ['LEGAL', 'Privacidad', 'La política de privacidad definitiva se completará antes del lanzamiento según los servicios realmente utilizados, incluidos hosting, autenticación, pagos y analítica.'], withdrawal: ['LEGAL', 'Derecho de desistimiento', 'La información definitiva sobre desistimiento se preparará antes del lanzamiento según el catálogo real y los requisitos legales aplicables.'] },
    languages: { de: 'DE', en: 'EN', es: 'ES' }
  }
}



