import React, { useState } from 'react'
import { LockKeyhole, ShieldCheck } from 'lucide-react'
import { useCart } from '../contexts/CartContext'
import { createCheckoutSession } from '../lib/api'
import { Link } from 'react-router-dom'
import { useLanguage } from '../i18n'
export default function Checkout() { const { items, subtotal } = useCart(); const { language, t } = useLanguage(); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ email: '', firstName: '', lastName: '', address: '', zip: '', city: '', country: 'DE' }); const shipping = items.length ? 4.9 : 0; const total = subtotal + shipping
  async function submit(e) { e.preventDefault(); setLoading(true); setError(''); try { const data = await createCheckoutSession({ items: items.map(({ id, quantity }) => ({ id, quantity })), customer: form, language }); if (data.url) window.location.href = data.url; else throw new Error(t('checkout.stripeError')) } catch (err) { setError(err.message); setLoading(false) } }
  if (!items.length) return <div className="screen-state"><h1>{t('checkout.empty')}</h1><Link className="button button--dark" to="/shop">{t('home.shop')}</Link></div>
  return <div className="page"><section className="page-hero page-hero--small"><p className="eyebrow">{t('checkout.eyebrow')}</p><h1>{t('checkout.title')}</h1></section><section className="section checkout"><form className="checkout-form" onSubmit={submit}><div className="form-section"><h2>{t('checkout.contact')}</h2><label>{t('checkout.email')}<input type="email" required value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></label></div><div className="form-section"><h2>{t('checkout.addressTitle')}</h2><div className="form-grid"><label>{t('checkout.firstName')}<input required value={form.firstName} onChange={e => setForm({...form,firstName:e.target.value})}/></label><label>{t('checkout.lastName')}<input required value={form.lastName} onChange={e => setForm({...form,lastName:e.target.value})}/></label></div><label>{t('checkout.address')}<input required value={form.address} onChange={e => setForm({...form,address:e.target.value})}/></label><div className="form-grid"><label>{t('checkout.zip')}<input required value={form.zip} onChange={e => setForm({...form,zip:e.target.value})}/></label><label>{t('checkout.city')}<input required value={form.city} onChange={e => setForm({...form,city:e.target.value})}/></label></div><label>{t('checkout.country')}<select value={form.country} onChange={e => setForm({...form,country:e.target.value})}><option value="DE">{t('checkout.countries.DE')}</option><option value="AT">{t('checkout.countries.AT')}</option><option value="ES">{t('checkout.countries.ES')}</option></select></label></div>{error && <div className="form-error">{error}</div>}<button className="button button--dark button--full" disabled={loading}>{loading ? t('checkout.loading') : <>{t('checkout.payment')} <LockKeyhole size={16}/></>}</button></form><aside className="summary checkout-summary"><h2>{t('checkout.order')}</h2>{items.map(item => { const p = item.translations?.[language] || item.translations?.de || item; return <div className="summary-line" key={item.id}><span>{p.name} × {item.quantity}</span><strong>{(item.price * item.quantity).toFixed(2).replace('.', ',')} €</strong></div>})}<hr/><div><span>{t('cart.shipping')}</span><strong>{shipping.toFixed(2).replace('.', ',')} €</strong></div><div className="summary__total"><span>{t('cart.total')}</span><strong>{total.toFixed(2).replace('.', ',')} €</strong></div><div className="trust"><ShieldCheck size={18}/><span>{t('checkout.secure')}</span></div></aside></section></div> }
