import React, { useEffect, useState } from 'react'
import { Edit3, FileText, Plus, Save, X } from 'lucide-react'
import { supabase } from '../../lib/supabase'

const EMPTY = { slug: '', title: '', excerpt: '', body: '', published: true }

export default function Content() {
  const [pages, setPages] = useState([]); const [editor, setEditor] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function load() { if (!supabase) { setError('Supabase ist nicht konfiguriert.'); setLoading(false); return } setLoading(true); const { data, error: dbError } = await supabase.from('content_pages').select('*').order('title'); if (dbError) setError(dbError.message); else setPages(data || []); setLoading(false) }
  useEffect(() => { load() }, [])
  async function save(e) { e.preventDefault(); setSaving(true); setError(''); setNotice(''); const payload = { slug: editor.slug.trim().toLowerCase(), title: editor.title.trim(), excerpt: editor.excerpt || '', body: editor.body || '', published: Boolean(editor.published), updated_at: new Date().toISOString() }; const result = editor.id ? await supabase.from('content_pages').update(payload).eq('id', editor.id) : await supabase.from('content_pages').insert(payload); if (result.error) setError(result.error.code === '23505' ? 'Dieser Slug existiert bereits.' : result.error.message); else { setEditor(null); setNotice('Inhalt gespeichert.'); await load() } setSaving(false) }
  return <div><div className="admin-page-head"><div><p className="eyebrow">CMS</p><h1>Inhalte</h1><p className="admin-subtitle">Texte und Inhaltsseiten der Store-Verwaltung</p></div><button className="button button--dark" onClick={() => setEditor({...EMPTY})}><Plus size={16}/> Seite hinzufügen</button></div>{error && <div className="form-error admin-error">{error}</div>}{notice && <div className="admin-success">{notice}</div>}<section className="admin-panel">{loading ? <div className="admin-loading">Inhalte werden geladen…</div> : pages.length === 0 ? <div className="empty-state"><FileText size={26}/><h2>Noch keine Inhalte</h2><p>Lege deine erste Inhaltsseite an.</p></div> : <div className="content-list">{pages.map(page => <div key={page.id}><div><strong>{page.title}</strong><small>/{page.slug} · {page.published ? 'Veröffentlicht' : 'Entwurf'}</small></div><button className="text-link" onClick={() => setEditor({...page})}><Edit3 size={15}/> Bearbeiten</button></div>)}</div>}</section>{editor && <div className="admin-modal-backdrop"><div className="admin-modal"><div className="admin-modal__head"><div><p className="eyebrow">CMS</p><h2>{editor.id ? 'Inhalt bearbeiten' : 'Seite hinzufügen'}</h2></div><button className="icon-button" onClick={() => !saving && setEditor(null)}><X size={18}/></button></div><form className="admin-form" onSubmit={save}><label>Titel<input required value={editor.title} onChange={e => setEditor(v => ({...v,title:e.target.value}))}/></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={editor.slug} onChange={e => setEditor(v => ({...v,slug:e.target.value.toLowerCase().replace(/\s+/g,'-')}))}/></label><label>Teaser<textarea rows="3" value={editor.excerpt || ''} onChange={e => setEditor(v => ({...v,excerpt:e.target.value}))}/></label><label>Inhalt<textarea rows="14" value={editor.body || ''} onChange={e => setEditor(v => ({...v,body:e.target.value}))}/></label><label className="checkbox-label"><input type="checkbox" checked={Boolean(editor.published)} onChange={e => setEditor(v => ({...v,published:e.target.checked}))}/> Veröffentlicht</label><div className="admin-modal__actions"><button type="button" className="button" onClick={() => setEditor(null)} disabled={saving}>Abbrechen</button><button className="button button--dark" disabled={saving}><Save size={16}/> {saving ? 'Speichern…' : 'Speichern'}</button></div></form></div></div>}</div>
}
