import React, { useEffect, useMemo, useState } from 'react'
import { Search, Users } from 'lucide-react'
import { supabase } from '../../lib/supabase'
import { formatDate, formatMoney } from '../../lib/admin'

export default function Customers() {
  const [orders, setOrders] = useState([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let active = true; (async () => { if (!supabase) { setError('Supabase ist nicht konfiguriert.'); setLoading(false); return } const { data, error: dbError } = await supabase.from('orders').select('id,email,first_name,last_name,address,postal_code,city,country,total,created_at').order('created_at', { ascending: false }); if (!active) return; if (dbError) setError(dbError.message); else setOrders(data || []); setLoading(false) })(); return () => { active = false } }, [])
  const customers = useMemo(() => { const map = new Map(); for (const order of orders) { const key = order.email.toLowerCase(); const c = map.get(key) || { email: order.email, first_name: order.first_name, last_name: order.last_name, postal_code: order.postal_code, city: order.city, country: order.country, orders: 0, total: 0, lastOrder: order.created_at }; c.orders += 1; c.total += Number(order.total || 0); if (new Date(order.created_at) > new Date(c.lastOrder)) c.lastOrder = order.created_at; map.set(key, c) } return [...map.values()] }, [orders])
  const filtered = customers.filter(c => `${c.email} ${c.first_name} ${c.last_name} ${c.city}`.toLowerCase().includes(query.toLowerCase()))
  return <div><div className="admin-page-head"><div><p className="eyebrow">CRM</p><h1>Kunden</h1><p className="admin-subtitle">{customers.length} eindeutige Kunden aus Bestellungen</p></div></div>{error && <div className="form-error admin-error">{error}</div>}<div className="admin-toolbar"><label className="search-field"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Name, E-Mail oder Ort suchen…"/></label></div><section className="admin-panel">{loading ? <div className="admin-loading">Kundendaten werden geladen…</div> : filtered.length === 0 ? <div className="empty-state"><Users size={26}/><h2>Noch keine Kunden</h2><p>Kunden werden automatisch aus den Bestellungen ermittelt.</p></div> : <div className="admin-table admin-table--responsive"><div className="admin-row admin-row--head"><span>Kunde</span><span>Ort</span><span>Bestellungen</span><span>Umsatz</span><span>Letzte Bestellung</span></div>{filtered.map(c => <div className="admin-row" key={c.email}><span><strong>{c.first_name} {c.last_name}</strong><small>{c.email}</small></span><span>{c.postal_code || ''} {c.city || '—'}</span><span>{c.orders}</span><span>{formatMoney(c.total)}</span><span>{formatDate(c.lastOrder)}</span></div>)}</div>}</section></div>
}
