import React, { useEffect, useState } from 'react'
import { Save, ShieldCheck } from 'lucide-react'
import { useAuth } from '../../contexts/AuthContext'
import { supabase } from '../../lib/supabase'

const DEFAULTS = { store_name: 'Gelobtes Land', domain: 'https://odenwald-honig.com', default_language: 'de', shipping_price: 4.9, free_shipping_threshold: 60 }

export default function Settings() {
  const { profile } = useAuth(); const [settings, setSettings] = useState(DEFAULTS); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  useEffect(() => { (async () => { if (!supabase) { setError('Supabase ist nicht konfiguriert.'); setLoading(false); return } const { data, error: dbError } = await supabase.from('store_settings').select('*').eq('id', 1).maybeSingle(); if (dbError) setError(dbError.message); else if (data) setSettings({ store_name: data.store_name, domain: data.domain, default_language: data.default_language, shipping_price: Number(data.shipping_price), free_shipping_threshold: Number(data.free_shipping_threshold) }); setLoading(false) })() }, [])
  async function save(e) { e.preventDefault(); setSaving(true); setError(''); setNotice(''); const payload = { ...settings, shipping_price: Number(settings.shipping_price), free_shipping_threshold: Number(settings.free_shipping_threshold), updated_at: new Date().toISOString(), updated_by: profile?.id || null }; const { error: dbError } = await supabase.from('store_settings').upsert({ id: 1, ...payload }, { onConflict: 'id' }); if (dbError) setError(dbError.message); else setNotice('Einstellungen gespeichert.'); setSaving(false) }
  return <div><div className="admin-page-head"><div><p className="eyebrow">STORE</p><h1>Einstellungen</h1></div></div>{error && <div className="form-error admin-error">{error}</div>}{notice && <div className="admin-success">{notice}</div>}{loading ? <div className="admin-loading">Einstellungen werden geladen…</div> : <form className="admin-panel settings-list" onSubmit={save}><label>Shopname<input value={settings.store_name} onChange={e => setSettings(v => ({...v,store_name:e.target.value}))}/></label><label>Domain<input type="text" value={settings.domain} onChange={e => setSettings(v => ({...v,domain:e.target.value}))}/></label><label>Standardsprache<select value={settings.default_language} onChange={e => setSettings(v => ({...v,default_language:e.target.value}))}><option value="de">Deutsch</option><option value="en">English</option><option value="es">Español</option></select></label><div className="form-grid"><label>Versand (€)<input type="number" min="0" step="0.01" value={settings.shipping_price} onChange={e => setSettings(v => ({...v,shipping_price:e.target.value}))}/></label><label>Versandkostenfrei ab (€)<input type="number" min="0" step="0.01" value={settings.free_shipping_threshold} onChange={e => setSettings(v => ({...v,free_shipping_threshold:e.target.value}))}/></label></div><div className="setup-note"><ShieldCheck size={17}/><span>Nur Administratoren können diese Einstellungen ändern. Geheimnisse wie Stripe-Keys oder der Supabase Service Role Key gehören nicht in dieses Formular.</span></div><button className="button button--dark" disabled={saving}><Save size={16}/> {saving ? 'Speichern…' : 'Einstellungen speichern'}</button></form>}</div>
}
